version: '3'

services:
  nosta_app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
      - .:/code
    container_name: nosta_app
    networks:
      - prasic
    environment:
      - DJANGO_SETTINGS_MODULE="production"
    labels:
      - traefik.enable=true
      - traefik.http.routers.nosta_app.rule=Host(`nosta.${DOMAIN}`)
      - traefik.http.routers.nosta_app.entrypoints=https
      - traefik.http.routers.nosta_app.tls=true
      - traefik.http.services.nosta_app.loadbalancer.server.port=8000
      - traefik.http.routers.nosta_app.tls.certresolver=${CERT_RESOLVER}
  
  docs_wp_db:
    image: mariadb:10.4
    volumes:
      - docs_wp_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  docs:
    depends_on:
      - docs_wp_db
    image: wordpress:latest
    restart: always
    volumes:
      - docs_wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: docs_wp_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    labels:
      - traefik.enable=true
      - traefik.http.routers.docs.rule=Host(`docs.${DOMAIN}`)
      - traefik.http.routers.docs.entrypoints=https
      - traefik.http.routers.docs.tls=true
      - traefik.http.routers.docs.tls.certresolver=${CERT_RESOLVER}

networks:
  prasic:
    external: true

volumes:
  docs_wp_data:
  docs_wp_db_data: