version: '3'

services:
  nosta_app:
    build:
      context: .
      dockerfile: ./production_Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: nosta_app
    depends_on:
      - nosta_db
    networks:
      - prasic
    environment:
      - DJANGO_SETTINGS_MODULE=nosta.settings.production
    volumes:
      - .:/usr/src/app/
    stdin_open: true
    tty: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.nosta_app.rule=Host(`nosta.${DOMAIN}`)
      - traefik.http.routers.nosta_app.entrypoints=https
      - traefik.http.routers.nosta_app.tls=true
      - traefik.http.services.nosta_app.loadbalancer.server.port=8000
      - traefik.http.routers.nosta_app.tls.certresolver=${CERT_RESOLVER}

  nosta_db:
    image: mariadb:10.6.4
    restart: always
    container_name: nosta_db
    networks:
      - prasic
    environment:
      MARIADB_ROOT_PASSWORD: nosta_db_root_password
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  prasic:
    external: true
